### ISSUE TITLE
节点数量的统计

### ISSUE THREAD

**Issue by shen-cheng-yu** [sdingcn/binary-tree-visualization#1]
请问，readme文档里的测试数据，32个节点数量是怎么算的，所有的非空节点加上#的数量并没有32啊

**Comment by syqszu** [comment]
> 

是自己输入的最大的节点数吧。你可以试试把它改小或者改大。

**Comment by sdingcn** [comment]
是指每行能容纳的最多节点数量。程序根据此数值调整节点大小。
